name: Daily Wakefit Report

on:
  schedule:
    # Runs daily at 9:30 AM UTC (3:00 PM IST)
    - cron: '30 9 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-daily-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Test secret
      run: |
        echo "Test secret value: ${{ secrets.TEST_SECRET }}"
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create credentials file
      run: |
        echo "Checking if GOOGLE_CREDENTIALS secret exists..."
        if [ -z "${{ secrets.GOOGLE_CREDENTIALS }}" ]; then
          echo "ERROR: GOOGLE_CREDENTIALS secret is empty or not set"
          exit 1
        fi
        echo "Creating scripts/credentials.json file..."
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > scripts/credentials.json
        echo "✓ credentials.json file created successfully in scripts/"
        python -c "import json; json.load(open('scripts/credentials.json'))" || (echo 'Invalid JSON format' && exit 1)

    
    - name: Create token file if exists
      run: |
        if [ ! -z "${{ secrets.GOOGLE_TOKEN }}" ]; then
          echo '${{ secrets.GOOGLE_TOKEN }}' > token.json
        fi
    
    - name: Run daily report script
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        cd scripts
        python automated_mail_WTS.py
    
    - name: Clean up sensitive files
      if: always()
      run: |
        rm -f credentials.json token.json
